import time
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fib(n):
  a = 1
  b = 1
  while(a + b < n):
    res = a + b
    a = b
    b = res
    if res % 2 == 0:
      yield res

t = time.process_time()
print(sum(fib(4000000)))
print('solved in {:.10f}'.format(time.process_time() - t, ))
